const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];

const icons = {
  bot: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3 5 7v9l7 4 7-4V7l-7-4Z"/><path d="M9 11h.01M15 11h.01M9 15h6"/></svg>',
  check: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg>',
  info: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20Z"/><path d="M12 16v-4M12 8h.01"/></svg>',
  ticket: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 4h16v16H4z"/><path d="M8 9h8M8 13h8M8 17h5"/></svg>',
  shield: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 3 7 3v5c0 4.7-2.9 8-7 10-4.1-2-7-5.3-7-10V6l7-3Z"/><path d="m9 12 2 2 4-4"/></svg>'
};

const initialState = () => ({
  conversationId: `CV-${Date.now().toString().slice(-8)}`,
  phase: 'welcome',
  scenario: '',
  title: '',
  os: '',
  attempt: 0,
  urgency: '一般',
  messages: [],
  screenshots: [],
  issueDescription: '',
  troubleshooting: [],
  ticket: null,
  tickets: [],
  ticketDraft: null,
  resolved: false
});

let state = initialState();
let typingNode = null;
let actionLocked = false;
let selectedTicketId = null;
let welcomePlayed = false;
let welcomeTimer = null;
let storageWarningShown = false;
const welcomePrefix = '你好，晓晨。IT 问题，';
const welcomeEnding = '一起解决。';

function finishWelcomeTyping() {
  clearTimeout(welcomeTimer);
  welcomeTimer = null;
  $('#welcomePrefix').textContent = welcomePrefix;
  $('#welcomeEnding').textContent = welcomeEnding;
  $('#welcomeTitle').classList.remove('is-typing');
}

function playWelcomeTyping() {
  if (welcomePlayed) return;
  welcomePlayed = true;
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
  const prefixChars = Array.from(welcomePrefix);
  const endingChars = Array.from(welcomeEnding);
  const length = prefixChars.length + endingChars.length;
  let index = 0;
  $('#welcomePrefix').textContent = '';
  $('#welcomeEnding').textContent = '';
  $('#welcomeTitle').classList.add('is-typing');
  function typeNext() {
    index++;
    $('#welcomePrefix').textContent = prefixChars.slice(0, index).join('');
    $('#welcomeEnding').textContent = endingChars.slice(0, Math.max(0, index - prefixChars.length)).join('');
    if (index < length) welcomeTimer = setTimeout(typeNext, 85);
    else finishWelcomeTyping();
  }
  welcomeTimer = setTimeout(typeNext, 180);
}

const views = { welcome: $('#welcomeView'), chat: $('#chatView') };
const messagesEl = $('#messages');
const heroInput = $('#heroInput');
const chatInput = $('#chatInput');
const heroSend = $('#heroSend');
const chatSend = $('#chatSend');

function escapeHTML(value) {
  return String(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
}

function formatTime(date = new Date()) {
  return new Intl.DateTimeFormat('zh-CN', { hour: '2-digit', minute: '2-digit', hour12: false }).format(date);
}

function saveState() {
  if (state.ticket) {
    const index = state.tickets.findIndex(ticket => ticket.id === state.ticket.id);
    if (index >= 0) state.tickets[index] = state.ticket;
    else state.tickets.push(state.ticket);
  }
  try { localStorage.setItem('xiaoqi-it-demo', JSON.stringify(state)); } catch (_) {
    if (!storageWarningShown) toast('浏览器存储空间不足或不可用，当前内容仅保留到页面关闭，请勿刷新');
    storageWarningShown = true;
  }
  updateSidebar();
}

function upgradeFeedbackMessages(messages) {
  const isOldConfirmation = message => message?.role === 'assistant' && (
    message.html.startsWith('<p>好的，我已记录这一步。<strong>现在问题解决了吗？</strong>') ||
    message.html.startsWith('<p>确认一下：完成第二步检查后，问题是否已经恢复？</p>')
  );
  return messages.filter((message, index) => {
    if (isOldConfirmation(message)) return false;
    // These were generated by the removed completion buttons, not free-form replies.
    const isOldCompletion = message.role === 'user' && [
      '<p>我已经按步骤操作完成了</p>', '<p>已经检查过了</p>'
    ].includes(message.html);
    return !(isOldCompletion && isOldConfirmation(messages[index + 1]));
  }).map(message => {
    if (message.role !== 'assistant') return message;
    return {
      ...message,
      html: message.html
        .replace(/<button\b[^>]*data-action="cannot-do"[^>]*>[\s\S]*?<\/button>/g, '')
        .replace(/(<button\b[^>]*data-action="handoff"[^>]*>)直接转人工(<\/button>)/g, '$1转人工$2')
        .replace(
        /<button class="quick-action primary" data-action="(?:step-done|second-done)">[^<]*<\/button>/g,
        '<button class="quick-action success" data-action="solved">已解决</button><button class="quick-action" data-action="not-solved">仍未解决</button>'
      )
    };
  });
}

function loadState() {
  try {
    const saved = JSON.parse(localStorage.getItem('xiaoqi-it-demo'));
    if (saved && saved.conversationId && Array.isArray(saved.messages)) {
      state = saved;
      state.screenshots = saved.screenshots || [];
      state.troubleshooting = saved.troubleshooting || [];
      state.tickets = Array.isArray(saved.tickets) ? saved.tickets : [];
      if (state.ticket) {
        const stored = state.tickets.find(ticket => ticket.id === state.ticket.id);
        if (stored) state.ticket = stored;
        else {
          state.ticket = { ...state.ticket, draft: { ...state.ticketDraft }, scenario: state.scenario, conversationId: state.conversationId };
          state.tickets.push(state.ticket);
        }
      }
      state.messages = upgradeFeedbackMessages(state.messages);
      try { localStorage.setItem('xiaoqi-it-demo', JSON.stringify(state)); } catch (_) { /* keep the upgraded view in memory */ }
    }
  } catch (_) { state = initialState(); }
}

function updateSidebar() {
  const hasSession = state.phase !== 'welcome';
  $('#historyItem').classList.toggle('has-session', hasSession);
  $('#historyTitle').textContent = hasSession ? (state.title || 'IT 服务会话') : '还没有服务记录';
  $('#historyTime').textContent = hasSession ? `今天 ${formatTime()}` : '发起问题后会自动保存';
  $('#ticketCount').textContent = String(state.tickets.length);
}

function closeNavigation() {
  $('#sidebar').classList.remove('open');
  $('#sidebarScrim').classList.add('hidden');
  $('#menuButton').setAttribute('aria-expanded', 'false');
}

function activateNavigation(name) {
  $$('[data-nav]').forEach(button => {
    const active = button.dataset.nav === name;
    button.classList.toggle('active', active);
    if (active) button.setAttribute('aria-current', 'page');
    else button.removeAttribute('aria-current');
  });
  $('#ticketsView').classList.toggle('hidden', name !== 'tickets');
  closeNavigation();
}

function showChat() {
  finishWelcomeTyping();
  activateNavigation('assistant');
  views.welcome.classList.add('hidden');
  views.chat.classList.remove('hidden');
  $('#conversationTitle').textContent = state.title || 'IT 服务会话';
  $('#conversationId').textContent = state.conversationId;
  requestAnimationFrame(() => chatInput.focus());
}

function showWelcome() {
  activateNavigation('assistant');
  views.chat.classList.add('hidden');
  views.welcome.classList.remove('hidden');
  playWelcomeTyping();
  requestAnimationFrame(() => heroInput.focus());
}

function ticketDate(value, fallback = '未记录日期') {
  return value ? new Intl.DateTimeFormat('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(value)) : fallback;
}

function renderTicketList() {
  const tickets = [...state.tickets].reverse();
  $('#ticketsSummary').textContent = `共 ${tickets.length} 条工单`;
  $('#ticketList').innerHTML = tickets.length ? `<ul class="ticket-list-grid">${tickets.map(ticket => `
    <li><button type="button" class="ticket-list-item" data-action="ticket-detail" data-ticket-id="${escapeHTML(ticket.id)}">
      <span class="ticket-list-copy"><span class="ticket-number">${escapeHTML(ticket.id)}</span><strong>${escapeHTML(ticket.draft?.title || 'IT 服务请求')}</strong><span class="ticket-list-updated">更新于 ${escapeHTML(ticketDate(ticket.updatedISO, ticket.updatedAt))}</span></span>
      <span class="ticket-list-tail"><span class="status-badge">${escapeHTML(ticket.status)}</span><span class="ticket-list-open">查看详情 →</span></span>
    </button></li>`).join('')}</ul>` : `<div class="ticket-empty">${icons.ticket}<h2>还没有工单</h2><p>有 IT 问题？先和小启聊聊。<br>需要人工协助时，提交的工单会出现在这里。</p><button type="button" class="button-primary" data-action="back-assistant">向助手提问</button></div>`;
}

function showTickets() {
  finishWelcomeTyping();
  activateNavigation('tickets');
  views.welcome.classList.add('hidden');
  views.chat.classList.add('hidden');
  renderTicketList();
  $('#ticketsTitle').focus();
}

function renderTicketDetail(ticket) {
  const d = ticket.draft || {};
  $('#ticketDetailBody').innerHTML = `${ticketStatusHTML(ticket)}<dl class="ticket-fields">${Object.entries({
    '问题摘要': d.summary || '未记录', '当前环境': d.environment || '未提供',
    '已尝试操作': d.attempts || '无排障记录', '紧急程度': d.urgency || '未提供',
    '处理节点': ticket.node, '处理团队': ticket.assignee, '创建时间': ticketDate(ticket.createdISO, ticket.createdAt)
  }).map(([label, value]) => `<div><dt>${escapeHTML(label)}</dt><dd>${escapeHTML(value)}</dd></div>`).join('')}</dl>${screenshotEvidenceHTML(d.screenshots)}`;
}

function openTicketDetail(id) {
  const ticket = state.tickets.find(item => item.id === id);
  if (!ticket) return toast('未找到该工单，请重新打开工单列表');
  selectedTicketId = id;
  renderTicketDetail(ticket);
  $('#ticketDetailDialog').showModal();
}

// Mock ITop response. A production adapter would query ITop here.
function updateMockTicket(ticket) {
  ticket.status = '处理中';
  ticket.assignee = ticket.scenario === 'software' ? '应用与授权支持组' : '网络与终端支持组';
  ticket.node = ticket.assignee;
  ticket.updatedISO = new Date().toISOString();
  ticket.updatedAt = formatTime();
  if (state.ticket?.id === ticket.id) state.ticket = ticket;
  saveState();
  renderTicketList();
}

async function refreshTicketDetail() {
  const ticket = state.tickets.find(item => item.id === selectedTicketId);
  const button = $('#refreshTicketDetail');
  if (!ticket || button.disabled) return;
  button.disabled = true;
  button.textContent = '正在查询…';
  try {
    await new Promise(resolve => setTimeout(resolve, 650));
    updateMockTicket(ticket);
    if (selectedTicketId === ticket.id) renderTicketDetail(ticket);
    toast('工单进度已更新');
  } finally {
    button.disabled = false;
    button.textContent = '刷新进度';
  }
}

function addMessage(role, html, options = {}) {
  const item = { role, html, screenshotId: options.screenshotId, system: Boolean(options.system), time: formatTime() };
  state.messages.push(item);
  renderMessage(item);
  saveState();
  scrollMessages();
  return item;
}

function renderMessage(item) {
  const row = document.createElement('article');
  row.className = `message-row ${item.role}${item.system ? ' system' : ''}`;
  if (item.role === 'assistant' && !item.system) row.innerHTML = `<div class="message-avatar">${icons.bot}</div><div class="message-content"><div class="message-name">小启 IT · ${item.time}</div><div class="bubble">${item.html}</div></div>`;
  else if (item.role === 'user') row.innerHTML = `<div class="message-content"><div class="message-name" style="text-align:right">你 · ${item.time}</div><div class="bubble">${screenshotHTML(state.screenshots.find(s => s.id === item.screenshotId))}${item.html}</div></div>`;
  else row.innerHTML = `<div class="message-content" style="max-width:100%;width:100%"><div class="bubble">${item.html}</div></div>`;
  messagesEl.appendChild(row);
}

function renderAllMessages() {
  messagesEl.innerHTML = '';
  state.messages.forEach(renderMessage);
  scrollMessages(false);
}

function screenshotHTML(shot) {
  if (!shot || !/^data:image\/(png|jpeg|webp);base64,/.test(shot.preview)) return '';
  return `<button type="button" class="screenshot-thumb" data-screenshot="${escapeHTML(shot.id)}" aria-label="查看截图：${escapeHTML(shot.name)}"><img src="${shot.preview}" alt="${escapeHTML(shot.name)}" /></button>`;
}

function screenshotEvidenceHTML(shots = []) {
  if (!shots?.length) return '';
  return `<div class="image-analysis"><strong>问题截图 · ${shots.length} 张</strong><div class="ticket-screenshots">${shots.map(screenshotHTML).join('')}</div><p class="image-analysis-label">截图及识别记录随模拟工单保存，仅在本机。</p></div>`;
}

function scrollMessages(smooth = true) {
  requestAnimationFrame(() => messagesEl.scrollTo({ top: messagesEl.scrollHeight, behavior: smooth ? 'smooth' : 'auto' }));
}

function showTyping(label = '正在理解问题并检索企业知识…') {
  if (typingNode) return;
  typingNode = document.createElement('article');
  typingNode.className = 'message-row assistant';
  typingNode.innerHTML = `<div class="message-avatar">${icons.bot}</div><div class="message-content"><div class="message-name">小启 IT · 正在处理</div><div class="bubble"><div class="typing" aria-label="${label}" title="${label}"><span></span><span></span><span></span></div></div></div>`;
  messagesEl.appendChild(typingNode);
  scrollMessages();
}

function hideTyping() {
  typingNode?.remove();
  typingNode = null;
}

async function assistantReply(html, delay = 650, phase) {
  showTyping();
  actionLocked = true;
  await new Promise(resolve => setTimeout(resolve, delay));
  hideTyping();
  addMessage('assistant', html);
  if (phase) setProgress(phase);
  actionLocked = false;
}

function setProgress(activeStep) {
  const order = ['understand', 'clarify', 'knowledge', 'result'];
  const activeIndex = order.indexOf(activeStep);
  $$('.progress-list li').forEach((li, index) => {
    li.classList.toggle('done', index < activeIndex);
    li.classList.toggle('active', index === activeIndex);
    const stepCircle = li.querySelector(':scope > span');
    if (index < activeIndex) stepCircle.innerHTML = icons.check;
    else if (!stepCircle.textContent.trim()) stepCircle.textContent = String(index + 1);
  });
}

function updateFacts(entries) {
  const facts = { '提问人': '林晓晨', '设备': state.os || '待确认', '状态': '处理中', ...entries };
  $('#contextFacts').innerHTML = Object.entries(facts).map(([key, value]) => `<div><dt>${escapeHTML(key)}</dt><dd>${escapeHTML(value)}</dd></div>`).join('');
}

function detectScenario(text) {
  if (/密码|token|密钥|secret/i.test(text)) return 'sensitive';
  if (/工单.*(进度|状态|怎么样)|处理到哪|ticket/i.test(text)) return 'status';
  if (/人工|提单|创建工单|提交工单/.test(text)) return 'handoff';
  if (/vpn|认证|远程办公/i.test(text)) return 'vpn';
  if (/网络|wifi|wi-fi|上网|联网/i.test(text)) return 'network';
  if (/软件|figma|申请|安装|权限/i.test(text)) return 'software';
  if (/天气|吃饭|写诗|旅游/.test(text)) return 'nonit';
  return 'generic';
}

function beginConversation(text) {
  const value = text.trim();
  if (!value || actionLocked) return;
  if (state.phase === 'welcome') {
    state.phase = 'active';
    state.title = value.length > 24 ? `${value.slice(0, 24)}…` : value;
    state.scenario = detectScenario(value);
    showChat();
  }
  addMessage('user', `<p>${escapeHTML(value)}</p>`);
  $('#conversationTitle').textContent = state.title;
  updateFacts({ '状态': '理解问题' });
  routeUserInput(value);
}

async function routeUserInput(text) {
  if (state.screenshots.length && await routeScreenshotText(text)) return;
  if (state.attempt && !state.ticket && state.phase === 'active') {
    if (/^(已解决|已经解决了?|解决了|好了|恢复了|我已完成)[！!。\s]*$/.test(text)) {
      await markResolved(true);
      return;
    }
    if (/^(仍未解决|未解决|还是不行|没用|没有用|无效|不行)[！!。\s]*$/.test(text)) {
      await handleUnresolved(true);
      return;
    }
  }
  const scenario = detectScenario(text);
  if (scenario === 'sensitive') {
    await assistantReply(`<p>为了保护账号安全，请不要在对话中发送密码、Token 或密钥。我不会记录或复述这类信息。</p><div class="warning-card">${icons.shield}<span><strong>已触发敏感信息保护</strong><br>请只描述错误提示和发生场景，不要提供真实凭据。</span></div><div class="quick-actions"><button class="quick-action" data-action="restart-question">重新描述问题</button><button class="quick-action" data-action="handoff">转人工</button></div>`, 500, 'clarify');
    return;
  }
  if (scenario === 'status') { await showTicketStatus(); return; }
  if (scenario === 'handoff') { await startHandoff('user_request'); return; }
  if (scenario === 'nonit') {
    await assistantReply('<p>我目前主要处理企业 IT 服务问题，例如网络、VPN、账号、软件和设备故障。你可以直接描述遇到的 IT 现象，我来帮你判断下一步。</p>', 500, 'clarify');
    return;
  }
  if (scenario === 'software') {
    state.scenario = 'software';
    state.title = '申请 Figma 专业版软件';
    updateFacts({ '设备': '公司电脑', '问题类型': '软件申请', '状态': '需要人工操作' });
    await assistantReply(`<p>我理解你需要申请 <strong>Figma 专业版</strong>。这涉及软件授权和成本审批，V1 不会自动开通权限，需要由 IT 人员继续处理。</p><p>我已保留你的诉求，你无需重新填写传统工单。</p><div class="knowledge-card"><div class="knowledge-head">${icons.ticket}<div><strong>已匹配企业流程</strong><small>《办公软件申请与授权规范》· 2026-08-15 更新</small></div></div><div class="knowledge-source"><span>IT 官方知识 · 相关度 96%</span><button data-action="source">查看依据</button></div></div><div class="quick-actions"><button class="quick-action primary" data-action="handoff">生成申请工单</button><button class="quick-action" data-action="cancel-handoff">暂不申请</button></div>`, 780, 'result');
    return;
  }
  if (scenario === 'vpn' || scenario === 'network' || scenario === 'generic') {
    state.scenario = scenario === 'generic' ? 'vpn' : scenario;
    const understood = state.scenario === 'network' ? '公司网络连接异常' : state.scenario === 'vpn' ? 'VPN 认证失败' : 'IT 故障';
    updateFacts({ '问题': understood, '状态': '等待环境信息' });
    await assistantReply(`<p>收到。我先确认一个最关键的信息，避免给你不适用的步骤：<strong>这台电脑使用什么系统？</strong></p><div class="quick-actions"><button class="quick-action" data-action="choose-os" data-value="Windows 11">Windows</button><button class="quick-action" data-action="choose-os" data-value="macOS 15">macOS</button><button class="quick-action" data-action="unknown-os">不确定</button></div>`, 720, 'clarify');
  }
}

async function chooseOS(os) {
  if (actionLocked || state.os) return;
  state.os = os;
  addMessage('user', `<p>${escapeHTML(os)}</p>`);
  updateFacts({ '设备': os, '状态': '检索企业知识' });
  if (state.scenario === 'network') await showNetworkStep();
  else await showVpnStep();
}

async function showVpnStep() {
  if (state.screenshots.length) return showScreenshotStep('vpn');
  state.attempt = 1;
  state.troubleshooting.push({ step: '清理 VPN 旧会话并重新认证', result: '已提供步骤，待用户反馈' });
  await assistantReply(`<p>已确认是 <strong>${escapeHTML(state.os)}</strong>。根据 IT 官方知识，认证失败最常见的原因是旧会话未清理。先做这一组低风险操作：</p><div class="knowledge-card"><div class="knowledge-head">${icons.shield}<div><strong>清理 VPN 旧会话并重新认证</strong><small>预计 1 分钟 · 不会修改系统配置</small></div></div><ol class="step-list"><li>完全退出「Qiyun Connect」客户端，而不是只关闭窗口。</li><li>等待 10 秒后重新打开，确认登录账号为公司邮箱。</li><li>重新连接「员工远程办公」节点。</li></ol><div class="knowledge-source"><span>《VPN 常见故障处理指南》· 2026-09-02</span><button data-action="source">查看原文</button></div></div><div class="quick-actions"><button class="quick-action success" data-action="solved">已解决</button><button class="quick-action" data-action="not-solved">仍未解决</button><button class="quick-action" data-action="handoff">转人工</button></div>`, 900, 'knowledge');
  updateFacts({ '设备': state.os, '已尝试': '清理 VPN 旧会话', '状态': '等待操作结果' });
}

async function showNetworkStep() {
  if (state.screenshots.length) return showScreenshotStep('network');
  state.attempt = 1;
  state.troubleshooting.push({ step: '重新获取公司网络连接', result: '已提供步骤，待用户反馈' });
  await assistantReply(`<p>已确认是 <strong>${escapeHTML(state.os)}</strong>。先用最小步骤判断是本机连接还是办公网络问题：</p><div class="knowledge-card"><div class="knowledge-head">${icons.shield}<div><strong>重新获取公司网络连接</strong><small>预计 1 分钟 · 安全操作</small></div></div><ol class="step-list"><li>关闭 Wi-Fi，等待 10 秒后重新开启。</li><li>忘记「Qiyun-Staff」网络并重新连接。</li><li>打开任意网页确认是否恢复。</li></ol><div class="knowledge-source"><span>《办公区网络连接指南》· 2026-08-28</span><button data-action="source">查看原文</button></div></div><div class="quick-actions"><button class="quick-action success" data-action="solved">已解决</button><button class="quick-action" data-action="not-solved">仍未解决</button><button class="quick-action" data-action="handoff">转人工</button></div>`, 900, 'knowledge');
  updateFacts({ '设备': state.os, '已尝试': '重新获取网络连接', '状态': '等待操作结果' });
}

async function handleUnresolved(feedbackAdded = false) {
  if (actionLocked || state.resolved || state.ticket || state.phase === 'handoff') return;
  if (state.troubleshooting.length) state.troubleshooting.at(-1).result = '用户反馈仍未解决';
  if (state.attempt < 2) {
    await secondTroubleshoot(feedbackAdded);
  } else {
    if (!feedbackAdded) addMessage('user', '<p>仍未解决</p>');
    await startHandoff('troubleshooting_failed');
  }
}

async function secondTroubleshoot(feedbackAdded = false) {
  state.attempt = 2;
  if (state.troubleshooting.length) state.troubleshooting.at(-1).result = '用户反馈仍未解决';
  state.troubleshooting.push({ step: state.scenario === 'network' ? '判断办公区网络范围' : '校验系统时间与账号状态', result: '已提供步骤，待用户反馈' });
  if (!feedbackAdded) addMessage('user', '<p>仍未解决</p>');
  updateFacts({ '已尝试': state.scenario === 'network' ? '重连网络（无效）' : '清理旧会话（无效）', '状态': '继续排障' });
  const isNetwork = state.scenario === 'network';
  const content = isNetwork
    ? `<li>检查其他同事是否也无法连接公司网络。</li><li>如果只有你的设备异常，请保存工作后重启电脑再试一次。</li>`
    : `<li>打开系统日期与时间设置，开启“自动设置时间”。</li><li>确认公司邮箱密码近期没有变更；不要在此处发送密码。</li>`;
  await assistantReply(`<p>上一方案无效，我不会重复推荐。再检查最后一条有可靠依据的路径：</p><div class="knowledge-card"><div class="knowledge-head">${icons.info}<div><strong>${isNetwork ? '判断办公区网络范围' : '校验系统时间与账号状态'}</strong><small>第二步排障 · 已结合上一步结果</small></div></div><ol class="step-list">${content}</ol><div class="knowledge-source"><span>${isNetwork ? '《办公网络事件判断手册》' : '《VPN 认证错误码说明》'} · IT 官方</span><button data-action="source">查看原文</button></div></div><div class="quick-actions"><button class="quick-action success" data-action="solved">已解决</button><button class="quick-action" data-action="not-solved">仍未解决</button><button class="quick-action" data-action="handoff">转人工</button></div>`, 820, 'knowledge');
}

async function markResolved(feedbackAdded = false) {
  if (actionLocked || state.resolved || state.ticket) return;
  state.resolved = true;
  if (state.troubleshooting.length) state.troubleshooting.at(-1).result = '用户确认已解决';
  state.phase = 'resolved';
  if (!feedbackAdded) addMessage('user', '<p>已解决</p>');
  $('#conversationStatus').textContent = '已自助解决';
  updateFacts({ '设备': state.os || '公司电脑', '状态': '已自助解决', '结果': '无需创建工单' });
  await assistantReply(`<p>太好了，本次服务已标记为 <strong>AI 自助解决</strong>，不会创建人工工单。</p><div class="resolved-card"><div class="resolved-icon">${icons.check}</div><strong>问题已解决</strong><p>本次排障记录已经保存。请为这次服务打分：</p><div class="rating" aria-label="服务评分">${[1,2,3,4,5].map(n => `<button type="button" data-action="rate" data-value="${n}" aria-label="${n} 分">★</button>`).join('')}</div></div>`, 520, 'result');
  saveState();
}

function buildTicketDraft() {
  if (state.screenshots.length) return buildScreenshotTicketDraft();
  const isSoftware = state.scenario === 'software';
  const isNetwork = state.scenario === 'network';
  return {
    title: isSoftware ? '申请 Figma 专业版授权' : isNetwork ? '公司网络无法连接，多轮自助排障未恢复' : 'VPN 认证失败，多轮自助排障未恢复',
    summary: isSoftware ? '用户因产品设计工作需要申请 Figma 专业版授权，需 IT 核实授权余量并发起审批。' : isNetwork ? `用户在 ${state.os || '公司电脑'} 上无法连接 Qiyun-Staff，重新连接网络并完成范围判断后仍未恢复。` : `用户在 ${state.os || '公司电脑'} 上连接 VPN 时提示认证失败，清理旧会话并校验系统时间后仍未恢复。`,
    environment: state.os || '公司电脑（具体系统待 IT 确认）',
    attempts: isSoftware ? 'AI 已确认该请求需要人工授权与审批' : state.attempt > 1 ? (isNetwork ? '1. 重连 Wi-Fi：无效；2. 判断故障范围并重启：无效' : '1. 清理 VPN 旧会话：无效；2. 校验系统时间与账号状态：无效') : '已完成首轮自助排查，问题未恢复',
    status: isSoftware ? '等待授权审批' : '故障仍在持续',
    urgency: state.urgency
  };
}

async function startHandoff(reason = 'user_request') {
  if (actionLocked || state.ticket) return;
  state.phase = 'handoff';
  state.ticketDraft = state.ticketDraft || buildTicketDraft();
  const reasonText = reason === 'image_boundary' ? '截图已保留，但现有演示知识不足以可靠处理此问题' : reason === 'troubleshooting_failed' ? '已有可靠自助路径均未解决问题' : state.scenario === 'software' && !state.screenshots.length ? '该请求需要人工完成授权与审批' : '你主动选择了人工协助';
  updateFacts({ '状态': '整理人工工单', '转人工原因': reasonText });
  await assistantReply(`<p><strong>建议转由 IT 人员继续处理。</strong>${escapeHTML(reasonText)}。前面的对话和排障记录都已保留，你不需要重新描述。</p><p>提交前只差一个必要信息：这个问题是否已经影响你当前的核心工作？</p><div class="quick-actions"><button class="quick-action danger" data-action="urgency" data-value="紧急">是，已影响工作</button><button class="quick-action" data-action="urgency" data-value="一般">否，可以等待</button></div>`, 650, 'result');
}

function ticketCardHTML() {
  const d = state.ticketDraft;
  return `<p>我已从当前对话中整理好工单，请确认内容：</p><div class="ticket-card"><div class="ticket-card-header"><strong>ITop 工单预览</strong><span>${escapeHTML(d.urgency)}</span></div><dl class="ticket-fields"><div><dt>问题标题</dt><dd>${escapeHTML(d.title)}</dd></div><div><dt>问题摘要</dt><dd>${escapeHTML(d.summary)}</dd></div><div><dt>当前环境</dt><dd>${escapeHTML(d.environment)}</dd></div><div><dt>已尝试操作</dt><dd>${escapeHTML(d.attempts)}</dd></div><div><dt>当前状态</dt><dd>${escapeHTML(d.status)}</dd></div></dl>${screenshotEvidenceHTML(d.screenshots)}<div class="ticket-actions"><button class="button-secondary" data-action="edit-ticket">修改</button><button class="button-primary" data-action="submit-ticket">确认提交</button></div></div>`;
}

async function setUrgency(value) {
  state.urgency = value;
  state.ticketDraft = buildTicketDraft();
  state.ticketDraft.urgency = value;
  addMessage('user', `<p>${value === '紧急' ? '是，已经影响我工作' : '不紧急，可以等待'}</p>`);
  await assistantReply(ticketCardHTML(), 550, 'result');
}

function openEditDialog() {
  const d = state.ticketDraft;
  $('#ticketTitleInput').value = d.title;
  $('#ticketSummaryInput').value = d.summary;
  $('#ticketUrgencyInput').value = d.urgency;
  $('#editDialog').showModal();
}

function saveTicketEdits(event) {
  event.preventDefault();
  const title = $('#ticketTitleInput').value.trim();
  const summary = $('#ticketSummaryInput').value.trim();
  if (!title || !summary) return;
  state.ticketDraft = { ...state.ticketDraft, title, summary, urgency: $('#ticketUrgencyInput').value };
  $('#editDialog').close();
  addMessage('assistant', `<p>修改已保存，请再次确认最终内容：</p>${ticketCardHTML()}`);
  toast('工单内容已更新');
}

async function submitTicket(button) {
  if (actionLocked || state.ticket) return;
  actionLocked = true;
  button.disabled = true;
  const oldText = button.textContent;
  button.textContent = '正在提交…';
  await new Promise(resolve => setTimeout(resolve, 1150));
  const now = new Date();
  const day = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}`;
  let number = state.tickets.length + 1;
  while (state.tickets.some(ticket => ticket.id === `INC-${day}-${String(number).padStart(4, '0')}`)) number++;
  const id = `INC-${day}-${String(number).padStart(4, '0')}`;
  state.ticket = { id, status: '已受理', node: '服务台分派', createdAt: formatTime(now), updatedAt: formatTime(now), createdISO: now.toISOString(), updatedISO: now.toISOString(), assignee: 'IT 服务台', draft: { ...state.ticketDraft }, scenario: state.scenario, conversationId: state.conversationId };
  state.phase = 'ticket-created';
  $('#conversationStatus').textContent = '已转人工';
  updateFacts({ '状态': '已创建工单', '工单号': id, '紧急程度': state.ticketDraft.urgency });
  addMessage('assistant', `<p>工单已经成功创建，IT 人员可以直接看到完整上下文和排障记录。</p>${ticketStatusHTML()}<div class="quick-actions"><button class="quick-action primary" data-action="refresh-status">查看最新进度</button></div>`);
  actionLocked = false;
  button.textContent = oldText;
  saveState();
  toast(`工单 ${id} 创建成功`);
}

function ticketStatusHTML(t = state.ticket) {
  if (!t) return '';
  const inProgress = t.status === '处理中';
  return `<div class="status-card"><div class="status-top"><div class="ticket-number">${escapeHTML(t.id)}</div><span class="status-badge">${escapeHTML(t.status)}</span></div><div class="status-subtitle">${escapeHTML(t.draft?.title || 'IT 服务请求')} · 更新于 ${escapeHTML(ticketDate(t.updatedISO, t.updatedAt))}</div><ol class="timeline"><li>工单已创建 · ${escapeHTML(ticketDate(t.createdISO, t.createdAt))}</li><li class="${inProgress ? '' : 'current'}">服务台已受理并校验信息</li>${inProgress ? `<li class="current">${escapeHTML(t.assignee)} 正在处理</li>` : '<li>等待分派至专业支持组</li>'}</ol></div>`;
}

async function showTicketStatus(id) {
  const ticket = id ? state.tickets.find(item => item.id === id) : state.ticket || (state.tickets.length === 1 ? state.tickets[0] : null);
  if (!ticket && state.tickets.length > 1) {
    await assistantReply(`<p>你有多条工单，想查看哪一条？</p><div class="quick-actions">${[...state.tickets].reverse().map(item => `<button class="quick-action" data-action="query-ticket" data-ticket-id="${escapeHTML(item.id)}">${escapeHTML(item.id)} · ${escapeHTML(item.draft?.title || 'IT 服务请求')}</button>`).join('')}</div>`, 400, 'result');
    return;
  }
  if (!ticket) {
    await assistantReply(`<p>当前账号下还没有本次 Demo 创建的工单。你可以先体验一次排障并转人工，或者从示例问题中选择「申请办公软件」。</p><div class="quick-actions"><button class="quick-action" data-action="restart-question">发起一个问题</button></div>`, 480, 'result');
    return;
  }
  await assistantReply(`<p>找到了这条工单，当前进度如下：</p>${ticketStatusHTML(ticket)}<div class="quick-actions"><button class="quick-action primary" data-action="refresh-status" data-ticket-id="${escapeHTML(ticket.id)}">刷新状态</button></div>`, 600, 'result');
}

async function refreshTicketStatus(id = state.ticket?.id) {
  const ticket = state.tickets.find(item => item.id === id);
  if (!ticket || actionLocked) return;
  showTyping('正在向 ITop 查询最新状态…');
  actionLocked = true;
  await new Promise(resolve => setTimeout(resolve, 900));
  hideTyping();
  updateMockTicket(ticket);
  addMessage('assistant', `<p>已从 ITop 获取到最新状态：工单已分派，支持团队正在处理。我不会自行推测预计完成时间。</p>${ticketStatusHTML(ticket)}`);
  actionLocked = false;
  saveState();
}

function toast(message) {
  const node = document.createElement('div');
  node.className = 'toast';
  node.innerHTML = `${icons.check}<span>${escapeHTML(message)}</span>`;
  $('#toastRegion').appendChild(node);
  setTimeout(() => node.remove(), 3200);
}

function resetDemo(confirmFirst = true) {
  if (actionLocked || $('#refreshTicketDetail').disabled) return toast('当前操作正在处理中，请稍后再试');
  if (confirmFirst && (state.phase !== 'welcome' || state.tickets.length) && !window.confirm('确定重置 Demo 吗？当前本地会话和模拟工单会被清除。')) return;
  state = initialState();
  saveState();
  prepareNewConversation();
}

function startNewConversation() {
  if (actionLocked) return toast('当前操作正在处理中，请稍后再试');
  const tickets = state.tickets;
  state = { ...initialState(), tickets };
  saveState();
  prepareNewConversation();
}

function prepareNewConversation() {
  if (typeof clearPendingScreenshot === 'function') clearPendingScreenshot();
  actionLocked = false;
  hideTyping();
  messagesEl.innerHTML = '';
  heroInput.value = '';
  chatInput.value = '';
  heroSend.disabled = true;
  chatSend.disabled = true;
  $('#conversationStatus').textContent = '正在处理';
  setProgress('clarify');
  updateFacts({});
  updateSidebar();
  showWelcome();
}

function autoResize(textarea) {
  textarea.style.height = 'auto';
  textarea.style.height = `${Math.min(textarea.scrollHeight, textarea === heroInput ? 140 : 110)}px`;
}

function handleTextarea(event, sendButton) {
  autoResize(event.target);
  sendButton.disabled = !event.target.value.trim() && !(typeof pendingScreenshot !== 'undefined' && pendingScreenshot);
  if (event.target === chatInput) $('#inputCount').textContent = `${event.target.value.length} / 500`;
}

function submitFrom(input) {
  if (actionLocked) return toast('正在处理上一条消息，请稍候');
  const text = input.value;
  const attachment = typeof pendingScreenshot !== 'undefined' ? pendingScreenshot : null;
  if (!text.trim() && !attachment) return;
  input.value = '';
  input.style.height = 'auto';
  heroSend.disabled = true;
  chatSend.disabled = true;
  $('#inputCount').textContent = '0 / 500';
  if (attachment) sendScreenshot(text, attachment);
  else beginConversation(text);
}

$('#heroForm').addEventListener('submit', event => { event.preventDefault(); submitFrom(heroInput); });
$('#chatForm').addEventListener('submit', event => { event.preventDefault(); submitFrom(chatInput); });
[heroInput, chatInput].forEach(input => {
  input.addEventListener('input', event => handleTextarea(event, input === heroInput ? heroSend : chatSend));
  input.addEventListener('keydown', event => {
    if (event.key === 'Enter' && !event.shiftKey && !event.isComposing) {
      event.preventDefault();
      submitFrom(input);
    }
  });
});

$$('[data-prompt]').forEach(button => button.addEventListener('click', () => beginConversation(button.dataset.prompt)));
$('#newChatButton').addEventListener('click', startNewConversation);
$('#resetButton').addEventListener('click', () => resetDemo(true));
$('#historyItem').addEventListener('click', () => { if (state.phase !== 'welcome') { showChat(); renderAllMessages(); } });
$('#saveTicketButton').addEventListener('click', saveTicketEdits);
$$('[data-nav]').forEach(button => button.addEventListener('click', () => {
  if (button.dataset.nav === 'tickets') showTickets();
  else if (state.phase === 'welcome') showWelcome();
  else showChat();
}));
$('#closeTicketDetail').addEventListener('click', () => $('#ticketDetailDialog').close());
$('#refreshTicketDetail').addEventListener('click', refreshTicketDetail);

document.addEventListener('click', async event => {
  const target = event.target.closest('[data-action]');
  if (!target || target.disabled || actionLocked) return;
  const action = target.dataset.action;
  if (action === 'choose-os') await chooseOS(target.dataset.value);
  else if (action === 'unknown-os') await chooseOS('Windows（根据设置界面判断）');
  else if (action === 'step-done' || action === 'second-done') await markResolved();
  else if (action === 'not-solved') await handleUnresolved();
  else if (action === 'solved') await markResolved();
  else if (action === 'handoff') await startHandoff('user_request');
  else if (action === 'handoff-failed') await handleUnresolved();
  else if (action === 'urgency') await setUrgency(target.dataset.value);
  else if (action === 'edit-ticket') openEditDialog();
  else if (action === 'submit-ticket') await submitTicket(target);
  else if (action === 'refresh-status') await refreshTicketStatus(target.dataset.ticketId || state.ticket?.id);
  else if (action === 'ticket-detail') openTicketDetail(target.dataset.ticketId);
  else if (action === 'query-ticket') await showTicketStatus(target.dataset.ticketId);
  else if (action === 'back-assistant') { if (state.phase === 'welcome') showWelcome(); else showChat(); }
  else if (action === 'source') toast('Demo：将跳转到有权限的企业知识原文');
  else if (action === 'rate') { $$('.rating button').forEach(button => button.classList.toggle('selected', Number(button.dataset.value) <= Number(target.dataset.value))); toast(`感谢你的 ${target.dataset.value} 分评价`); }
  else if (action === 'restart-question') startNewConversation();
  else if (action === 'cancel-handoff') { addMessage('user', '<p>暂不处理</p>'); await assistantReply('<p>好的，本次对话已经保留。需要时可以回来继续，或随时让我帮你创建工单。</p>', 350, 'result'); }
});

$('#menuButton').addEventListener('click', () => {
  const open = $('#sidebar').classList.toggle('open');
  $('#sidebarScrim').classList.toggle('hidden', !open);
  $('#menuButton').setAttribute('aria-expanded', String(open));
});
$('#sidebarScrim').addEventListener('click', () => {
  $('#sidebar').classList.remove('open');
  $('#sidebarScrim').classList.add('hidden');
  $('#menuButton').setAttribute('aria-expanded', 'false');
});

loadState();
updateSidebar();
if (state.phase === 'welcome') showWelcome();
else {
  showChat();
  renderAllMessages();
  $('#conversationStatus').textContent = state.resolved ? '已自助解决' : state.ticket ? '已转人工' : '正在处理';
  if (state.ticket) updateFacts({ '设备': state.os || '公司电脑', '状态': state.ticket.status, '工单号': state.ticket.id });
  else updateFacts({ '设备': state.os || '待确认', '状态': state.resolved ? '已自助解决' : '处理中' });
  setProgress(state.resolved || state.ticket || state.phase === 'handoff' ? 'result' : state.attempt ? 'knowledge' : 'clarify');
}
